---
- name: Adding EC2 Connection
  hosts: all
  gather_facts: false
  tasks:
  - name: create EC2 compute resource
    redhat.satellite.compute_resource:
      name: EC2_compute_resource
      description: EC2
      locations:
        - Default Location
      organizations:
        - Default Organization
      provider: EC2
      provider_params:
        user: "{{ AWS_ACCESS_KEY }}"
        password: "{{ AWS_ACCESS_PASSWORD }}"
        region: us-east-2
      server_url: "https://satellite.example.com"
      username: "admin"
      password: "{{ ADMIN_PASSWORD }}"
      state: present
