---
- name: Create A Subnet
  gather_facts: false 
  hosts: localhost
    roles:
      - role: redhat.satellite.subnets
        vars:
          satellite_server_url: https://satellite.example.com
          satellite_username: "admin"
          satellite_password: "{{ADMIN_PASSWORD }}"
          satellite_subnets:
            - name: "{{SUBNET_NAME }}"
              description: "{{ description }}"
              network: "192.168.0.0"
              mask: "255.255.255.192"
              gateway: "192.168.0.1"
              from_ip: "192.168.0.2"
              to_ip: "192.168.0.42"
              boot_mode: "Static"
              dhcp_proxy: "satellite.example.com"
              tftp_proxy: "satellite.example.com"
              dns_proxy: "satellite.example.com"
              vlanid: 452
              mtu: 9000
              domains:
              - "example.com"
              organizations:
              - "Default Organization"
              locations:
              - "Default Location"

