---
- name: Create A Domain 
  hosts: all
  gather_facts: false
  tasks:
  - name: domain
    redhat.satellite.domain:
    name: "{{ DOMAIN_NAME }"
    description: "{{ Domain_DESCRIPTIO }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "https://satellite.example.com"
    username: "admin"
    password: "{{ ADMIN_PASSWORD }}"
    state: present
