- name: Install Satellite Server
  hosts: all
  roles:
    - role: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_options:
          - '--foreman-initial-organization "Technology"'
          - '--foreman-initial-admin-password "redhat123$"'
